name: Chris Bisazza
favicon: null
layout_spectrum: 0.5346593728754669
typography_spectrum: 0.8064946222584695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12639996455982327
  lightness: 0.007445015944540501
  saturation: 0.01626451569609344
  rhythmicContrast: 0.0005552840884774923
purpose: []
